// <auto-generated />
using DataLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace DataLibrary.Migrations
{
    [DbContext(typeof(EFProjectContext))]
    [Migration("20180201073309_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DataLibrary.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressDetile");

                    b.Property<string>("AreaCode");

                    b.Property<string>("Emaile");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Poco");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Tel");

                    b.HasKey("Id");

                    b.ToTable("Addreses");
                });

            modelBuilder.Entity("DataLibrary.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AddressId");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataLibrary.Domain.OrderMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("PaymentType");

                    b.Property<string>("Poco");

                    b.Property<string>("SourceCode");

                    b.Property<string>("SourceName");

                    b.Property<decimal>("Total");

                    b.HasKey("Id");

                    b.ToTable("OrderMasters");
                });

            modelBuilder.Entity("DataLibrary.Domain.OrderStatu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Poco");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("DataLibrary.Domain.Customer", b =>
                {
                    b.HasOne("DataLibrary.Domain.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });
#pragma warning restore 612, 618
        }
    }
}
